apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  selector:
    app: swiggy-app
  ports:
  
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  type: NodePort
  
